name: Docker Image CI

on:
  push:
  #Tells what branch to push on.
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    name: Build a docker image and push to it my DockerHub repo

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo to runner
    - uses: actions/checkout@v2
    
    - name : Set up Docker Buildx
    - uses: docker/setup-buildx-actions@v1

    - name: Log into the DockerHub account
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #Command to build the image for Docker
    - name: Build and push the Docker image
    - id: docker_build
    - uses: docker/build-push-action@v2
    - with:
        push: true
        tag: ${{ secrets.DOCKER_USERNAME }}:latest
