name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
       #Docker Username within the Github Secrets
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         #Docker Password within Github Secrets
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         #Runs command to login into your docker account.
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag calmwizard890/my-project-repository:$(date +%s)
      
    - name: Docker Push
      run: docker push calmwizard890/my-project-repository
