name: Docker Image CI
# Command to run the workflow whenever a tag is pushed
on:
  #push:
    #tags:
      #- '*'
  push:
  #Tells what branch to push on.
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      env:
        # Docker Username within the Github Secrets
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        # Docker Password within Github Secrets
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # Runs command to log in to your docker account.
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Create Tag
      run: |
        git tag (date +%s)
        git push origin (date +%s)

    - name: Extract Git Tag
      id: extract_tag
      run: echo "TAG_VERSION=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

    # Command to build and push the image for Docker
    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        # Command to tag the pushed image based on the git tag version and latest
        context: .
        push: true
        tags: |
          calmwizard890/my-project-repository:$(date +%s)
          calmwizard890/my-project-repository:latest

    # Command to extract metadata from the repository
    - name: Extract Docker Metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: |
          calmwizard890/my-project-repository:$(date +%s)

    # Command to display said data
    - name: Display Docker Metadata
      run: |
        echo "Tags: ${{ steps.metadata.outputs.tags }}"
